# Generated by Django 3.0.8 on 2020-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='H:\\GitHub\\Pregunta-02\\Ruteo\\media/images/'),
        ),
    ]
